my:
  props2:
    map:
      aaa:
        emap:
          apple:
            map:
              xxx:
                bool: false

      bbb:
        emap:
          orange:
            map:
              yyy:
                bool: true
    list:
      - map:
          'b1':
            bool: true
    set:
      - emap:
          apple:
            map:
              'aaaa':
                 bool: true
  ### https://youtrack.jetbrains.com/issue/IDEA-291922 (boolean (Boolean) properties of POJO in Map<POJO>)
  newprops:
    props:
      foo:
        true-key: true
        false-key: off
    first-key: off
    second-key: false
  props:
    enum-list[0]: lit11
    enum-list[1]: lit12
    enum-list[2]: lit13
    string-list[0]: foo
    string-list[1]: bar
    string-list[2]: boo
    pojo-list:
      - str1: 'aaaaa'
      - str1: 'bbbbb'
    string-string-map:
      foo: 'bar'
      bar: 'boo'
    ## POJO[] arrays
    pojo2array:
      - id: first
        enum1-enum2-map:
          lit12: lit21
      - id: second
        enum-string-map:
          lit12: smth
        enum1-enum2-map:
          lit12: lit22
  diff-style:
    props:
      my-inner-class:
        inner-str-prop-one: foo
      prop-with-underscore: bar

